djangohtmx/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('htmx.urls'))
]

htmx/urls.py
from django.urls import path
from . import views
from htmx.views import index
app_name = 'htmx'
urlpatterns = [
    path('',views.index,name='index'),
    path('add',views.adduser,name='adduser'),
    path('delete/<event_id>/',views.delete_event,name='delete-event'),
    path('edit/<event_id>/',views.edit_event,name='edit-event'),

]

htmx/models.py
from django.db import models

# Create your models here.
class Login(models.Model):
     username = models.CharField(max_length=50, verbose_name='')
     salary = models.CharField(max_length=50, verbose_name='', default='')
     number = models.CharField(max_length=50, verbose_name='', default='')

htmx/views.py
from django.shortcuts import render,get_list_or_404,redirect
from .models import Login
from .form import LoginForm


def index(request):
    tabledata = [
        ['user'],
        ['sal'],
        ['num'],
        ['del']
    ]
    loginform = Login.objects.all()
    return render(request, 'index.html', {'tabledata': loginform})


def adduser(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
    context = {'form': form}
    if form.is_valid():
        form.save()
        return redirect('htmx:index')
    else:
        form = LoginForm()
    return render(request, 'add.html', context)
def delete_event(request,event_id):
    event=Login.objects.get(pk=event_id)
    event.delete()
    loginform = Login.objects.all()
    return render(request,'table.html',{'tabledata': loginform})
def edit_event(request,event_id):
    event=Login.objects.get(pk=event_id)
    if request.method == 'POST':
        form = LoginForm(request.POST,instance=event)
        if form.is_valid():
            new_event = form.save()
            return render(request,'tr.html',{'event':new_event})
    else:
        form = LoginForm(instance=event)
        return render(request,'edit.html',{'form':form,'event':event})

templates/add.html
<html>
<head>
    
    <script src="https://unpkg.com/htmx.org@1.9.10" integrity="sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC" crossorigin="anonymous"></script>
</head>
<body>
<form action="{% url 'htmx:adduser'%}" method="post">
    {% csrf_token %}
    
<table>
  <thead>
    <tr>
      <th><label>username</label></th>
      <th><label>salary</label></th>
      <th><label>number</label></th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>{{ form.username }}</td>
        <td>{{ form.salary }}</td>
        <td>{{ form.number }}</td>
    </tr>
  </tbody>
</table>
    <button>add<a href="http://127.0.0.1:8000" ></a></button>
    <br>
</form>
</body>
</html>

templates/edit.html
  <tr>
        <td>{{ form.username }}</td>
        <td>{{ form.salary }}</td>
        <td>{{ form.number }}</td>
        
        <td><button hx-post="{% url 'htmx:edit-event' event.id %}"  hx-swap="outerHTML" class="btn btn-outline-success btn-sm" hx-target="closest tr">save</button></td>
        
    </tr>
  

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://unpkg.com/htmx.org@1.9.10" integrity="sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC" crossorigin="anonymous"></script>
</head>
<body>
<form hx-post="{% url 'htmx:index'%}">
    {% csrf_token %}
{% include 'table.html' %}

</form>
</body>
</html>

templates/table.html
<table class="table">
  <thead>
    <tr>
      <th><label>username</label></th>
      <th><label>salary</label></th>
      <th><label>number</label></th>
        <th><label>DELETE</label></th>
    </tr>
  </thead>
  <tbody>
  {% for event in tabledata %}
    {% include 'tr.html' %}
      {% endfor %}
 
  
  </tbody>

</table>

templates/tr.html
  <tr>
          <td><label id="zusername">{{ event.username }}</label></td>
          <td><label id="zsalary">{{ event.salary }}</label></td>
          <td><label id="znumber">{{ event.number }}</label></td>
          <td><button hx-get="{% url 'htmx:delete-event' event.id %}" hx-target="closest tr" hx-swap="delete" class="btn btn-outline-danger btn-sm">Delete</button></td>
{#          <td><a href="{% url 'htmx:edit-event' event.id %}"  hx-swap="outerHTML" class="btn btn-outline-info btn-sm">edit</a></td>#}
          <td><button hx-get="{% url 'htmx:edit-event' event.id %}"  hx-swap="outerHTML" class="btn btn-outline-info btn-sm" hx-target="closest tr">edit</button></td>
  </tr>

templates/update.html
<html>
<head>
    
    <script src="https://unpkg.com/htmx.org@1.9.10" integrity="sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC" crossorigin="anonymous"></script>
</head>
<body>
<form action="{% url 'htmx:edit-event' event.id%}" method="post">
    {% csrf_token %}
    
<table>
  <thead>
    <tr>
      <th><label>username</label></th>
      <th><label>salary</label></th>
      <th><label>number</label></th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>{{ form.username }}</td>
        <td>{{ form.salary }}</td>
        <td>{{ form.number }}</td>
    </tr>
  </tbody>
</table>
    <input type="submit" name="edit">
    <br>
</form>
</body>
</html>